"""Material master rules, coding, and search helpers."""

from .coding import generate_next_item_code, next_sequence
from .batch_intake import (
    BatchFactExtraction,
    BatchMaterialIntakeAnalyzer,
    ExtractedMaterialFacts,
    MaterialIntakeBatchResult,
    MaterialIntakeDecision,
    MaterialIntakeRow,
)
from .item_creation import ItemCreationDraft, ItemMasterCreationPlanner
from .postgres_catalog import CatalogPaths, PostgresCatalogSearchClient, PostgresMaterialCatalog
from .release_resolver import (
    ReleaseMaterialCandidate,
    ReleaseMaterialResolver,
    load_current_published_catalog,
)
from .high_recall import (
    BatchMaterialJudgement,
    CandidateGroup,
    HighRecallBatchMaterialIntakeAnalyzer,
    HighRecallBatchResult,
    HighRecallCandidate,
    HighRecallMaterialRetriever,
    MaterialBatchJudgement,
    RetrievalResult,
)
from .intake_drafts import (
    MaterialDraftBatch,
    MaterialItemDraft,
    MaterialTypeDraft,
    build_material_drafts,
    revise_material_drafts,
)
from .runtime_aliases import RuntimeAliasStore
from .runtime_publications import (
    MaterialPublication,
    PublishedMaterialSku,
    PublishedMaterialType,
    RuntimeMaterialPublicationStore,
)
from .rules import ItemIntent, MaterialRules, prepare_item_from_intent
from .search import MaterialSearch, SearchCandidate
from .vector_retrieval import (
    HashingTextVectorizer,
    TextEmbeddingProvider,
    TextVectorIndex,
    VectorMatch,
    material_vector_text,
    normalize_vector_text,
)
from .type_classifier import (
    MaterialClassificationCandidate,
    MaterialClassificationResult,
    MaterialTypeClassifier,
)
from .tariff_extraction import (
    STAGES as TARIFF_EXTRACTION_STAGES,
    STAGE_LABELS as TARIFF_EXTRACTION_STAGE_LABELS,
    TARIFF_EXPECTED_BYTES,
    TARIFF_EXPECTED_PAGES,
    TARIFF_SOURCE_URL,
    TARIFF_SOURCE_VERSION,
    TariffExtractionJobManager,
    TariffHierarchyState,
    TariffNode,
    attach_parent_codes,
    collapse_hierarchy_nodes,
    parse_tariff_page_words,
    parse_tariff_scope_nodes,
    parse_tariff_page_text,
)
from .tariff_family_review import (
    DECISION_VERSION as TARIFF_FAMILY_DECISION_VERSION,
    FROZEN_RELEASE_VERSION as TARIFF_FAMILY_RELEASE_VERSION,
    REVIEW_VERSION as TARIFF_FAMILY_REVIEW_VERSION,
    FamilyCandidate,
    build_decision_template,
    build_review_package,
    build_review_slice,
    freeze_review_package,
    map_tariff_nodes,
    normalize_tariff_name,
)
from .tariff_attribute_review import (
    ATTRIBUTE_DECISION_VERSION,
    ATTRIBUTE_FROZEN_RELEASE_VERSION,
    ATTRIBUTE_REVIEW_VERSION,
    TariffAttributeRow,
    build_attribute_review,
    build_attribute_decision_template,
    compile_standard_type_sku_candidates,
    extract_tariff_attributes,
    freeze_attribute_review_package,
)
from .tariff_declaration import (
    DECLARATION_EXPECTED_PAGES,
    DECLARATION_SOURCE_URL,
    DECLARATION_SOURCE_VERSION,
    DECLARATION_STAGE_LABELS,
    DECLARATION_STAGES,
    DeclarationParserState,
    TariffDeclarationJobManager,
    TariffDeclarationProfile,
    load_declaration_profiles,
    normalize_declaration_code,
    normalize_declaration_text,
    parse_declaration_page_text,
    validate_declaration_profiles,
)
from .reference_catalog import (
    GPC_KIND_LABELS,
    GPC_KIND_LABELS_ZH,
    GPC_KIND_ORDER,
    GpcReferenceIndex,
)
from .procurement_templates import (
    ProcurementConstraint,
    ProcurementMainTemplate,
    ProcurementTemplateCatalog,
    ProcurementTemplateRegistry,
    ProcurementTypeProfile,
)
from .procurement_batch_pilot import (
    ClusterFact,
    ClusterJudgement,
    ProcurementBatchPilot,
    ProcurementBatchPilotJobManager,
    ProcurementCluster,
    ProcurementSourceRow,
    ProcurementWorkbookSnapshot,
    build_clusters,
    load_purchase_workbook,
)
from .procurement_batch_review import (
    ProcurementBatchReviewStore,
    ProcurementReviewRuleCatalog,
    source_decision_hash,
)
from .procurement_batch_publication import ProcurementBatchGpcPublisher
from .procurement_frequency_discovery import (
    DEFAULT_OUTPUT_ROOT as PROCUREMENT_FREQUENCY_OUTPUT_ROOT,
    DEFAULT_SOURCE_PATH as PROCUREMENT_FREQUENCY_SOURCE_PATH,
    build_clusters as build_procurement_frequency_clusters,
    discover as discover_procurement_frequency,
    read_source_rows as read_procurement_frequency_source_rows,
)
from .procurement_frequency_discovery_v0_2 import (
    DEFAULT_OUTPUT_ROOT as PROCUREMENT_FREQUENCY_V2_OUTPUT_ROOT,
    VERSION as PROCUREMENT_FREQUENCY_V2_VERSION,
    DiscoveryV2Row,
    build_clusters_v2 as build_procurement_frequency_clusters_v2,
    build_family_review_candidates as build_procurement_family_review_candidates,
    convert_rows as convert_procurement_frequency_rows_v2,
    discover_v2 as discover_procurement_frequency_v2,
)
from .procurement_frequency_discovery_v0_3 import (
    DEFAULT_OUTPUT_ROOT as PROCUREMENT_FREQUENCY_V3_OUTPUT_ROOT,
    VERSION as PROCUREMENT_FREQUENCY_V3_VERSION,
    DiscoveryV3Row,
    build_clusters_v3 as build_procurement_frequency_clusters_v3,
    build_family_review_candidates_v3 as build_procurement_family_review_candidates_v3,
    convert_rows_v3 as convert_procurement_frequency_rows_v3,
    discover_v3 as discover_procurement_frequency_v3,
)
from .procurement_frequency_discovery_v0_4 import (
    DEFAULT_OUTPUT_ROOT as PROCUREMENT_FREQUENCY_V4_OUTPUT_ROOT,
    VERSION as PROCUREMENT_FREQUENCY_V4_VERSION,
    build_review_queues_v4 as build_procurement_frequency_review_queues_v4,
    discover_v4 as discover_procurement_frequency_v4,
)
from .procurement_frequency_discovery_v0_5 import (
    DEFAULT_OUTPUT_ROOT as PROCUREMENT_FREQUENCY_V5_OUTPUT_ROOT,
    VERSION as PROCUREMENT_FREQUENCY_V5_VERSION,
    discover_v5 as discover_procurement_frequency_v5,
)
from .procurement_frequency_discovery_v0_6 import (
    DEFAULT_OUTPUT_ROOT as PROCUREMENT_FREQUENCY_V6_OUTPUT_ROOT,
    VERSION as PROCUREMENT_FREQUENCY_V6_VERSION,
    build_v6_review as build_procurement_frequency_review_v6,
    discover_v6 as discover_procurement_frequency_v6,
)

__all__ = [
    "CatalogPaths",
    "BatchFactExtraction",
    "BatchMaterialIntakeAnalyzer",
    "ExtractedMaterialFacts",
    "ItemIntent",
    "MaterialRules",
    "MaterialSearch",
    "MaterialClassificationCandidate",
    "MaterialClassificationResult",
    "MaterialIntakeBatchResult",
    "MaterialIntakeDecision",
    "MaterialIntakeRow",
    "MaterialTypeClassifier",
    "PostgresCatalogSearchClient",
    "PostgresMaterialCatalog",
    "ReleaseMaterialCandidate",
    "ReleaseMaterialResolver",
    "load_current_published_catalog",
    "BatchMaterialJudgement",
    "CandidateGroup",
    "HighRecallBatchMaterialIntakeAnalyzer",
    "HighRecallBatchResult",
    "HighRecallCandidate",
    "HighRecallMaterialRetriever",
    "MaterialBatchJudgement",
    "RetrievalResult",
    "RuntimeAliasStore",
    "RuntimeMaterialPublicationStore",
    "MaterialPublication",
    "PublishedMaterialSku",
    "PublishedMaterialType",
    "MaterialDraftBatch",
    "MaterialItemDraft",
    "MaterialTypeDraft",
    "build_material_drafts",
    "revise_material_drafts",
    "SearchCandidate",
    "HashingTextVectorizer",
    "TextEmbeddingProvider",
    "TextVectorIndex",
    "VectorMatch",
    "material_vector_text",
    "normalize_vector_text",
    "generate_next_item_code",
    "ItemCreationDraft",
    "ItemMasterCreationPlanner",
    "next_sequence",
    "prepare_item_from_intent",
    "TARIFF_EXTRACTION_STAGES",
    "TARIFF_EXTRACTION_STAGE_LABELS",
    "TARIFF_EXPECTED_BYTES",
    "TARIFF_EXPECTED_PAGES",
    "TARIFF_SOURCE_URL",
    "TARIFF_SOURCE_VERSION",
    "TariffExtractionJobManager",
    "TariffHierarchyState",
    "TariffNode",
    "attach_parent_codes",
    "collapse_hierarchy_nodes",
    "parse_tariff_page_words",
    "parse_tariff_scope_nodes",
    "parse_tariff_page_text",
    "TARIFF_FAMILY_REVIEW_VERSION",
    "TARIFF_FAMILY_DECISION_VERSION",
    "TARIFF_FAMILY_RELEASE_VERSION",
    "FamilyCandidate",
    "build_decision_template",
    "build_review_package",
    "build_review_slice",
    "freeze_review_package",
    "map_tariff_nodes",
    "normalize_tariff_name",
    "ATTRIBUTE_REVIEW_VERSION",
    "ATTRIBUTE_DECISION_VERSION",
    "ATTRIBUTE_FROZEN_RELEASE_VERSION",
    "TariffAttributeRow",
    "build_attribute_review",
    "build_attribute_decision_template",
    "compile_standard_type_sku_candidates",
    "extract_tariff_attributes",
    "freeze_attribute_review_package",
    "DECLARATION_EXPECTED_PAGES",
    "DECLARATION_SOURCE_URL",
    "DECLARATION_SOURCE_VERSION",
    "DECLARATION_STAGE_LABELS",
    "DECLARATION_STAGES",
    "DeclarationParserState",
    "TariffDeclarationJobManager",
    "TariffDeclarationProfile",
    "load_declaration_profiles",
    "normalize_declaration_code",
    "normalize_declaration_text",
    "parse_declaration_page_text",
    "validate_declaration_profiles",
    "GPC_KIND_LABELS",
    "GPC_KIND_LABELS_ZH",
    "GPC_KIND_ORDER",
    "GpcReferenceIndex",
    "ProcurementConstraint",
    "ProcurementMainTemplate",
    "ProcurementTemplateCatalog",
    "ProcurementTemplateRegistry",
    "ProcurementTypeProfile",
    "ClusterFact",
    "ClusterJudgement",
    "ProcurementBatchPilot",
    "ProcurementBatchPilotJobManager",
    "ProcurementCluster",
    "ProcurementSourceRow",
    "ProcurementWorkbookSnapshot",
    "build_clusters",
    "load_purchase_workbook",
    "ProcurementBatchReviewStore",
    "ProcurementReviewRuleCatalog",
    "source_decision_hash",
    "ProcurementBatchGpcPublisher",
    "PROCUREMENT_FREQUENCY_OUTPUT_ROOT",
    "PROCUREMENT_FREQUENCY_SOURCE_PATH",
    "build_procurement_frequency_clusters",
    "discover_procurement_frequency",
    "read_procurement_frequency_source_rows",
    "PROCUREMENT_FREQUENCY_V2_OUTPUT_ROOT",
    "PROCUREMENT_FREQUENCY_V2_VERSION",
    "DiscoveryV2Row",
    "build_procurement_frequency_clusters_v2",
    "build_procurement_family_review_candidates",
    "convert_procurement_frequency_rows_v2",
    "discover_procurement_frequency_v2",
    "PROCUREMENT_FREQUENCY_V3_OUTPUT_ROOT",
    "PROCUREMENT_FREQUENCY_V3_VERSION",
    "DiscoveryV3Row",
    "build_procurement_frequency_clusters_v3",
    "build_procurement_family_review_candidates_v3",
    "convert_procurement_frequency_rows_v3",
    "discover_procurement_frequency_v3",
    "PROCUREMENT_FREQUENCY_V4_OUTPUT_ROOT",
    "PROCUREMENT_FREQUENCY_V4_VERSION",
    "build_procurement_frequency_review_queues_v4",
    "discover_procurement_frequency_v4",
    "PROCUREMENT_FREQUENCY_V5_OUTPUT_ROOT",
    "PROCUREMENT_FREQUENCY_V5_VERSION",
    "discover_procurement_frequency_v5",
    "PROCUREMENT_FREQUENCY_V6_OUTPUT_ROOT",
    "PROCUREMENT_FREQUENCY_V6_VERSION",
    "build_procurement_frequency_review_v6",
    "discover_procurement_frequency_v6",
]
